### ISSUE TITLE
Removal of the dependency on boost

### ISSUE THREAD

**Issue by 370rokas** [bgamer50/BitGraph#2]
Hello,

Are there any plans to remove BitGraph's and associated library ([Gremlin++](https://github.com/bgamer50/Gremlin-), [Maelstrom](https://github.com/bgamer50/Maelstrom)) dependency on the boost library?

I've seen the minimum C++ version for Maelstorm is C++17, so `boost::any` and `boost::any_cast` can be replaced with the C++ standard library's alternatives (`std::any`, `std::any_cast`) which were introduced in C++17.

If there are no plans for this in the next release, would pull requests with the removal of the library be welcome?

**Comment by SteveGremory** [comment]
C++ 20 is stable anyways so it shouldn't really be a problem, most compilers support it.

**Comment by bgamer50** [comment]
> Hello,
> 
> Are there any plans to remove BitGraph's and associated library ([Gremlin++](https://github.com/bgamer50/Gremlin-), [Maelstrom](https://github.com/bgamer50/Maelstrom)) dependency on the boost library?
> 
> I've seen the minimum C++ version for Maelstorm is C++17, so `boost::any` and `boost::any_cast` can be replaced with the C++ standard library's alternatives (`std::any`, `std::any_cast`) which were introduced in C++17.
> 
> If there are no plans for this in the next release, would pull requests with the removal of the library be welcome?

Removing boost is planned for the upcoming 1.0.0 release, I just haven't got around to it yet with all the work I've been doing for what is essentially a complete rewrite of BitGraph.  For Maelstrom, I copied some of my prototype code, which used boost::any, so I ended up leaving that in, not wanting to accidentally break something, and now it's propagated across that library and up the stack to Gremlin++ and BitGraph.  But it is on my radar, and I do want to drop boost, it's just going to be probably near the September deadline that I'll finally get to that.

If you want to make a PR dropping it, then by all means go ahead.  Thanks for the interest in BitGraph!

**Comment by bgamer50** [comment]
> C++ 20 is stable anyways so it shouldn't really be a problem, most compilers support it.

Yeah, I also want to migrate to C++20 but I'm worried I'll accidentally break something, so I am probably going to do that after the 1.0.0 release in September.

**Comment by SteveGremory** [comment]
Could make a PR for that :)

**Comment by bgamer50** [comment]
Should be resolved now.
